baseURL = "https://strmcrown.dev/"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "strmcrown"

enableRobotsTXT = true

[pagination]
pagerSize = 10

[permalinks]
thoughts = "/thoughts/:slug/"
science = "/science/:slug/"
programs = "/programs/:slug/"
study = "/study/:slug/"
reading = "/reading/:slug/"
photos = "/photos/:slug/"
hacks-contests = "/hacks-contests/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "github-dark"
lineNos = false

[params]
author = "Viktor Savostyanov"
description = "Личный блог о программировании, AI, Data Science и исследованиях."

avatar = "/avatar.jpg"

accent = "#c47a3a"